web: python services:
  - type: worker
    name: alisa-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: BOT_TOKEN
        value: 123456789:ABCDefGhIjkLmNoPQRstuVwXyZ
